### ISSUE TITLE
Additional useful info in output of imaging pipeline

### ISSUE THREAD

**Issue by FredSchuller** [i4Ds/STIX-GSW#111]
The following changes / additions should be implemented in the imaging pipeline (this would be nice improvements but should not block the next release):

- time range: the data used to produce an image can cover a time range slightly different to the one input by the user, simply because the available data in the file has a given sampling rate; it would be important to store the start and end time actually used to compute the results in the output object

- total counts: the total counts found in the data to generate an image is currently displayed on screen by procedure stix_compute_vis_amp_phase.pro. Since this information can be useful for the subsequent analysis, it would be good to also include it in the output object

**Comment by paolomassa** [comment]
Hi @FredSchuller , I added selected time range and the total number of counts in the final map structure constructed with 'stx_make_map' (see draft pull request). Maybe the time range is redundant with the fields 'TIME' and 'DUR' of the map structure. Please, let me know if what I did is compliant with what you suggested or if you have better ideas on this

By the way, so far in the draft pull request only MEM_GE calls 'stx_make_map' since I'm waiting to receive some feedbacks on this procedure before modifying every other routine
