### ISSUE TITLE
Imaging demo not correcting for average aspect solution 

### ISSUE THREAD

**Issue by hannahc243** [i4Ds/STIX-GSW#68]
In the imaging demo, the average shift to map center (calculated from Frederic's average aspect solution - [26.1,58.2]) doesn't seem to be applied correctly. It seems to be added and subtracted, resulting in no change, i.e. the output map (bproj/clean) has the same map center as that given as input. 

I notice that it is subtracted in line 73 of stix2vis_sep2021:
 this_mapcenter = mapcenter - [26.1,58.2] ; Subtract Frederic's mean shift values

and added again in lines 24 & 25 of stx_bproj:
 b_map.xc = vis[0].xyoffset[0] + 26.1
 b_map.yc = vis[0].xyoffset[1] + 58.2

Similarly in stx_vis_clean, lines 349, 350:  
this_xc = vis[0].xyoffset[0] + 26.1
this_yc = vis[0].xyoffset[1] + 58.2

Note: I haven't checked the other imaging algorithms for this correction, so it may or may not also apply to those.

- IDL Version: IDL 8.8.0
- STIX GSW Version: 25-Mar-2022
- OS: Mac

<img width="900" alt="input_mapcenter" src="https://user-images.githubusercontent.com/76849369/161258146-d16332a2-5288-4581-912c-9ebde3e4da0d.png">

<img width="582" alt="output_clean_map_structure" src="https://user-images.githubusercontent.com/76849369/161258151-32a0df22-8cdd-4d2c-af3b-d69c2e4525b4.png">

**Comment by paolomassa** [comment]
Hi @hannahc243,

Thanks for double-checking. 

The idea behind the subtraction-addition of Frederic's mean values is the following. 
Assume that a flare takes place in (0'',0'') on the Sun surface (quasi-heliocentric coordinates, i.e. the spacecraft roll angle is not taken into account). Since STIX is pointing in (26.1'',58.2'') (mean SAS solution provided by Frederic), the flare appears in (-26.1'',-58.2'') in the coordinate system of the instrument (i.e., the one in which the image reconstruction is performed).  Line 73 of stix2vis_sep2021 is needed for applying an appropriate phase shift to the visibilities, so that the flare is reconstructed at the center of the map. However, as stated before, this map is defined in the STIX coordinate system; so  the map is centered in xc = -26.1'', yc = -58.2''. To conceive the map in the quasi-heliocentric coordinate system, we then need to shift the map center by using again the mean values provided by Frederic (but this time we have to add them). That is why we implemented the shifts of the centers of the reconstructed maps at the end of every algorithm. So, we obtain a map centered in (0'', 0'') with the flare reconstructed in the center as expected.

Does it make sense?

**Comment by samaloney** [comment]
This is great, a perfect example of why issues are good as now anyone who looks could find this 👍

@hannahc243 if @paolomassa answer makes sense feel free to close the issue or if not follow back up with him on here.

**Comment by hannahc243** [comment]
@paolomassa thanks for your response. I still have a few questions. So the final map is in the quasi heliocentric coordinate system. Does this mean that if we compare with another map, such as AIA in the STIX reference frame, we still need to apply an aspect correction to our output map to have the coordinates align? And shouldn't the position change due to roll angle correction also?

**Comment by paolomassa** [comment]
Hi @hannahc243.  The issue concerning the coordinate system of the STIX reconstructions is not trivial. Indeed, it would be good if @FredSchuller could have a look at the my answer below, so that we're sure to be on the same page on this.

For passing from the STIX reference frame (the one in which the reconstructions are performed) to the Heliocentric coordinate frame, we have to make the following corrections:

1. Rotate the STIX reconstruction by 90 degrees, for taking into account that the instrument itself is rotated by 90 degrees since it is mounted "on the wall" of the spacecraft;
2. Correct for the STIX pointing, i.e. take into account the the fact that Solar Orbiter is not pointing exactly at the center of the Sun and that there is an offset between the spacecraft optical axis and the STIX one. The latter should be a systematic offset, although we need to investigate this more in detail (it may depend on the temperature of other issues). Once you have performed this correction, the STIX map is in the coordinate frame of Solar Orbiter, which we also call quasi-Heliocentric, since the only correction left is the one for the spacecraft roll angle
3. Correct for the roll angle of Solar Orbiter.

Now, the first correction is already implemented for every imaging method. The second correction can be performed only when the Aspect solution is available and for now we implemented just an "average" Aspect solution (the one based on the values (26.1'',58.2'') provided by @FredSchuller). If you know the Aspect solution for a specific event, you have to "manually" insert this information in the STIX map. This is just a temporary situation since we are implementing an automatic way to perform the Aspect correction (when available). As for the third correction, we decided not to rotate the reconstructed STIX map, but to save the roll angle value in the map structure. This means that, when you plot a STIX map "alone" using the SSWIDL 'plot_map' procedure, you get something like the figure below:
 
<img width="483" alt="Schermata 2022-04-16 alle 17 59 23" src="https://user-images.githubusercontent.com/64010598/163682341-51a02c94-c9cf-4876-ab0f-3a724ec4138a.png">

As you may notice, the roll angle value changes the orientation of the grid defining the coordinates on the Sun surface. However, the (x,y) location of the STIX map does not change with the roll angle. So, the (x,y) values that are reported in the frame of the figure have to be considered in the coordinate frame of Solar Orbiter (assuming to have also performed the second correction of the list).
On the other hand, when you overlay a STIX map to a rotated AIA one using again 'plot_map', this procedure reads the roll angle value in the STIX map structure and  corrects the location and the orientation of the STIX map accordingly in order to have a meaningful comparison of the maps.

**Comment by hannahc243** [comment]
@paolomassa thanks for the clarification!

**Comment by FredSchuller** [comment]
Hi both, sorry for not reacting before... 
But, yes, the description outlined by Paolo does make sense, this is how the various systems are defined. Now we need to test the results and compare the flare location with other data (AIA-rotated or EUI for example), using a large sample of events at various positions!
