### ISSUE TITLE
Clarifications on stix_compute_vis_amp_phase function

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIX-GSW#75]
@paolomassa sorry for probably really obvious questions but while implementing the python version I came across some things I'm not sure about or I misunderstanding

This section of the code correct for the grid transmission but should the errors not be computed before this as they are related to the detected photons rather than the corrected photons incident on the grids?
https://github.com/i4Ds/STIX-GSW/blob/ba544c8289dcef0562f8235aadcc31c855290afb/stix/idl/processing/vis/stix_compute_vis_amp_phase.pro#L309-L330

This section of the code derives the error on the amplitude
https://github.com/i4Ds/STIX-GSW/blob/ba544c8289dcef0562f8235aadcc31c855290afb/stix/idl/processing/vis/stix_compute_vis_amp_phase.pro#L381-L384

If the amplitude is given by
<img src="https://render.githubusercontent.com/render/math?math=A=(R^2%2BI^2)^{1/2}C">
then I would have expected something like
<img src="https://render.githubusercontent.com/render/math?math=\Delta A = ( (\frac{R C}{(R^2%2BI^2)^{1/2}})^2 \Delta R^2 %2b (\frac{I C}{(R^2%2BI^2)^{1/2}})^2 \Delta I^2)^{1/2}">
I guess I'm missing something? Also if the systematic error is 5% would that term be `(syserr * ampobs^2)` rather then `syserr^2 * ampobs^2`?

Again probably really simple but when calculating the phase error here
https://github.com/i4Ds/STIX-GSW/blob/ba544c8289dcef0562f8235aadcc31c855290afb/stix/idl/processing/vis/stix_compute_vis_amp_phase.pro#L405
I can't seem to figure out where this comes from given 
<img src="https://render.githubusercontent.com/render/math?math=\phi = \text{arctan} (I/R)">
I was expecting something kinda like this 
<img src="https://render.githubusercontent.com/render/math?math=\Delta \phi = ((\frac{-I}{I^2%2BR^2})^2\Delta I^2 %2B (\frac{R}{I^2%2BR^2})^2\Delta R^2 )^{1/2}">

**Comment by paolomassa** [comment]
Hi @samaloney! No problem at all, I'll try to answer to 2 out of 3 questions:
- I haven't understood your question concerning the grid transmission and the error on the counts: can you reformulate it? Sorry for this!
- A visibility amplitudes is defined as 
<img src="https://render.githubusercontent.com/render/math?math=\vert V \vert = \alpha \sqrt{(C-A)^2 %2B (D-B)^2},">
where A,B,C and D are the number of counts recorded by the detector pixels. Hence, the formula for the error is pretty much the same you derived, but replacing the real and the imaginary part with C-A and D-B, respectively:
<img src="https://render.githubusercontent.com/render/math?math=\Delta\vert V \vert = \alpha \sqrt{\left(\frac{(C-A) \Delta(C-A)}{\sqrt{(C-A)^2 %2B (D-B)^2}}\right)^2 %2B  \left(\frac{(D-B) \Delta(D-B)}{\sqrt{(C-A)^2 %2B (D-B)^2}}\right)^2} = \alpha \sqrt{\left(\frac{(C-A) \Delta(C-A)}{\vert V \vert}\right)^2 %2B  \left(\frac{(D-B) \Delta(D-B)}{\vert V \vert}\right)^2}">

- As for the systematic error, I think we wrote a correct line since it is added in quadrature. I double checked, and in the vis_fwdfit code  that is in the gen folder of SSW there is an analogous line: visin.sigamp    = SQRT(visin.sigamp^2  + syserr^2 * visamp^2)

- The formula for error on a visibility phase was derived by Gordon as
<img src="https://render.githubusercontent.com/render/math?math=\Delta \phi = \frac{\Delta \vert V \vert}{\vert V \vert}">
For what I have understood, he derived this formula by making the same computations as yours and assuming 
<img src="https://render.githubusercontent.com/render/math?math=\Delta \vert V \vert = \Delta R = \Delta I">
However, I will investigate this more in detail

**Comment by samaloney** [comment]
Thanks I think it all clear now.

* Yes ignore the grid transmission question I see what's going on now, a good nights sleep helped.
* The amplitude error is also clear now.
* The systematic error look good too, I think I'll probably code up as  `(vsigamp^2 + (syserr * visamp)^2)`
* For the phase error I assume there some good reason it works but couldn't figure it out
